In [3]:
# tinh do dai vec to
import numpy as np
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

vector = np.array([3,4])
print(compute_vector_length(vector))

5.0


In [6]:
# tinh tich vo huong
import numpy as np
def compute_dot_product(vector1, vector2):
    #result = np.dot(vector1,vector2)
    #result = vector1.dot(vector2)
    result = vector1@vector2
    return result

vector1 = np.array([3,4])
vector2 = np.array([1,2])
print(compute_dot_product(vector1,vector2))

11


In [7]:
# nhan vector voi ma tran
import numpy as np
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result
matrix = np.array([[1,2],[3,4]])
vector = np.array([4,5])
print(matrix_multi_vector(matrix,vector))

[14 32]


In [8]:
# nhan ma tran voi ma tran
import numpy as np
def matrix_multi_matrix(matrix1, matrix2):
    result = np.dot(matrix1, matrix2)
    return result
matrix1 = np.array([[1,2],[3,4],[5,6]])
matrix2 = np.array([[1,2,3],[4,5,6]])
print(matrix_multi_matrix(matrix1,matrix2))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [11]:
# ma tran nghich dao
import numpy as np
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result
matrix = np.array([[1,2],[3,4]])
print(inverse_matrix(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
# eigenvector(v) va eigenvalues(lamda) Av = (lamda)v
import numpy as np
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors
matrix = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [4]:
# cosine similarity
import numpy as np
def compute_cosine(v1,v2):
    cos_sim = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
    return cos_sim
v1 = np.array([1,2,3,4])
v2 = np.array([1,0,3,0])
print(compute_cosine(v1,v2))

0.5773502691896257
